<?php $_settings = Mage::getStoreConfig('hb_ajaxizer/settings'); ?>
<?php if (isset($_settings['enable']) && $_settings['enable']): ?>
    <div class="hb-ajax-loading">
        <div><?php echo $this->__('loading...') ?></div>
    </div>
    <div class="hb-popup" style="display:none;">
        <div class="hb-close"></div>
        <div class="hb-content"></div>
    </div>
    <script type="text/javascript">
        var Ajaxizer = new HB_Ajaxizer(<?php echo json_encode($_settings) ?>);
    </script>
<?php endif; ?>